# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build single file linux-x64
      run: dotnet publish -c release -r linux-x64 -p:PublishSingleFile=true --self-contained true --verbosity Normal -p:PublishTrimmed=True -p:EnableCompressionInSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Build single file linux-arm64
      run: dotnet publish -c release -r linux-arm64 -p:PublishSingleFile=true --self-contained true --verbosity Normal -p:PublishTrimmed=True -p:EnableCompressionInSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Build single file macos-x64 (Intel)
      run: dotnet publish -c release -r osx-x64 -p:PublishSingleFile=true --self-contained true --verbosity Normal -p:PublishTrimmed=True -p:EnableCompressionInSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Build single file macos-arm64 (Apple Silicon)
      run: dotnet publish -c release -r osx-arm64 -p:PublishSingleFile=true --self-contained true --verbosity Normal -p:PublishTrimmed=True -p:EnableCompressionInSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Build single file windows-x64
      run: dotnet publish -c release -r win-x64 -p:PublishSingleFile=true --self-contained true --verbosity Normal -p:PublishTrimmed=True -p:EnableCompressionInSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Build single file windows-arm64
      run: dotnet publish -c release -r win-arm64 -p:PublishSingleFile=true --self-contained true --verbosity Normal -p:PublishTrimmed=True -p:EnableCompressionInSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Upload single file build linux-x64
      uses: actions/upload-artifact@v4
      with:
        name: KekUploadServer-linux-x64
        path: KekUploadServer/bin/Release/net8.0/linux-x64/publish/KekUploadServer
    - name: Upload single file build linux-arm64
      uses: actions/upload-artifact@v4
      with:
        name: KekUploadServer-linux-arm64
        path: KekUploadServer/bin/Release/net8.0/linux-arm64/publish/KekUploadServer
    - name: Upload single file build osx-x64
      uses: actions/upload-artifact@v4
      with:
        name: KekUploadServer-macos-x64
        path: KekUploadServer/bin/Release/net8.0/osx-x64/publish/KekUploadServer
    - name: Upload single file build osx-arm64
      uses: actions/upload-artifact@v4
      with:
        name: KekUploadServer-macos-arm64
        path: KekUploadServer/bin/Release/net8.0/osx-arm64/publish/KekUploadServer
    - name: Upload single file build windows-x64
      uses: actions/upload-artifact@v4
      with:
        name: KekUploadServer-windows-x64
        path: KekUploadServer/bin/Release/net8.0/win-x64/publish/KekUploadServer
    - name: Upload single file build windows-arm64
      uses: actions/upload-artifact@v4
      with:
        name: KekUploadServer-windows-arm64
        path: KekUploadServer/bin/Release/net8.0/win-arm64/publish/KekUploadServer
